Support custom base64 encoding in golang helper methods
EverythingMe/inbloom pull request #9
Opened 2019-05-26 06:44 UTC by bergundy

2019-05-26 06:45 UTC, bergundy commented
@dvirsky apparently I don't have write access to EverythingMe/inbloom.
PTAL

2019-06-13 09:39 UTC, dvirsky requested changes
If you feel strongly about keeping it that way just tell me and I'll approve.

2019-06-13 09:39 UTC, dvirsky commented on go/inbloom/bloom.go
> +func (f *BloomFilter) MarshalBase64(encoding ...*base64.Encoding) string {
I don't like this pattern so much. 
How about adding func (f *BloomFilter) MarshalBase64Encoding(encoding *base64.Encoding) and have the old function just call this one with nil?

2019-06-13 09:39 UTC, dvirsky commented on go/inbloom/bloom.go
> +func UnmarshalBase64(b64 string, encoding ...*base64.Encoding) (*BloomFilter, error) {
same here.

2019-06-17 07:39 UTC, bergundy commented
@dvirsky I like it better the way I did it. I'm merging so we can move forward.

2019-06-17 07:39 UTC, merged